version: "3"

services:
  redis-master:
    image: redis:7.0.0
    ports:
      - "6379:6379"
    volumes:
      - ./redis-master.conf/master.conf:/usr/local/etc/redis/master.conf
    command: redis-server /usr/local/etc/redis/master.conf

  redis-slave:
    image: redis:7.0.0
    ports:
      - "6380:6379"
    volumes:
      - ./redis-slave.conf/slave.conf:/usr/local/etc/redis/slave.conf
    command: redis-server /usr/local/etc/redis/slave.conf

  sentinel:
    image: redis:7.0.0
    ports:
      - "26379:26379"
    volumes:
      - ./redis-sentinel.conf/sentinel.conf:/usr/local/etc/redis/sentinel.conf
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf

