version: '3'

services:
  nginx:
    image: nginx:latest
    command: /bin/bash -c "chmod -R 777 /app/nginx_uploads && nginx -g 'daemon off;'"
    ports:
      - "8082:8082"
    volumes:
      - ./nginx.conf/nginx.conf:/etc/nginx/nginx.conf
      - /opt/homebrew/var/www:/app/nginx_uploads

volumes:
  nginx-uploads:
